language: node_js

node_js:
  - node

# Travis-CI Caching
cache:
  yarn: true
  npm: false
  directories:
    - node_modules

before_install:
  - export TZ=Asia/Shanghai

# S: Build LifeCycle
install:
  - npm install

# before_script:

script:
  # - npm run eslint # 工程测试
  # - npm run dev # 工程测试
  # - npm run clean # 清除缓存
  # - npm run gulp # 压缩
  - npm run dist # 工程构建打包

after_success:
  - cd ./public
  - git init
  - git config user.name "JoeyBling"
  - git config user.email "2434387555@qq.com"
  - git add .
  - git commit -m "deploy at `date +\"%Y-%m-%d %H:%M:%S\"`"
  - git push --force --quiet "https://${CI_TOKEN_GITHUB}@${GITHUB_REPO}" master:gh-pages
  - git push --force --quiet "https://${CI_TOKEN_GITEE}@${GITEE_REPO}" master:gh-pages

git:
  depth: false

branches:
  only:
    - master

# before_deploy:
#   - yarn build

deploy:
  # provider: pages
  # github-token: $GITHUB_TOKEN # github 上的token环境变量
  # local-dir: ./dist  # 根据情况自定义到静态文件输出目录
  # skip-cleanup: true
  # 默认为gh-pages
  # target-branch: gh-pages
  # email: 2434387555@qq.com
  # name: JoeyBling
  on:
    branch: master # 当master分支有push事件的时候执行deploy流程

env:
  global:
    - GITHUB_REPO: github.com/JoeyBling/yilia-plus-demo.git
    - GITEE_REPO: gitee.com/zhousiwei/yilia-plus-demo.git